/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ColorPicker.java
 *
 * Created on 09-jun-2011, 16:23:40
 */

package org.iesapp.modules.guardies.dialogs.cfg;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JColorChooser;
import javax.swing.JDialog;

/**
 *
 * @author Josep
 */
public class ColorPicker extends javax.swing.JPanel {

    /** Creates new form ColorPicker */
    public ColorPicker() {
        initComponents();
        mcolor = new Color(100,100,100);
        jLabel1.setOpaque(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("···");
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        final JColorChooser chooser = new JColorChooser();
        chooser.setColor(mcolor);

        ActionListener okListener = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                mcolor = chooser.getColor();
                jLabel1.setBackground(mcolor);
            }
        };

        ActionListener cancelListener = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
               //
            }
        };

        JDialog dialog = JColorChooser.createDialog(this, "Tria un color", false, chooser, okListener,
                cancelListener);
        dialog.setVisible(true);


        dialog.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
              // mcolor = chooser.getColor();
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

   public void setColor(Color color) {
        mcolor = color;
        jLabel1.setBackground(color);
    }

    public Color getColor() {
        return mcolor;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


    Color mcolor;
}
