/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Properties.java
 *
 * Created on 09-jun-2011, 16:27:14
 */

package org.iesapp.modules.guardies.dialogs.cfg;

import org.iesapp.modules.guardies.util.Cfg;

/**
 *
 * @author Josep
 */
public class Properties extends javax.swing.JPanel {
    private  Cfg cfg;

    /** Creates new form Properties */
    public Properties() {
        initComponents();
    }
   
    public void initialize(Cfg cfg) {
        this.cfg = cfg;

        jValidaSortida.setSelected(cfg.validaSortida);
        jActivaTarda.setSelected(cfg.activaTarda);
        jValidarse.setSelected(cfg.valida);
        jMissatges.setValue(cfg.activaMissatges);
        jMinRetras.setValue(cfg.activaPolicy);

        jNClicks.setSelectedIndex(cfg.nClick - 1);
        jLookFeel.setSelectedItem(cfg.lookAndFeel);
        jTipusLletra.setText(cfg.fontName);
        jMidaLletra.setValue(cfg.fontSize);
        jAlturaCella.setValue(cfg.alturaCella);
        jTactil.setSelected(cfg.tactil > 0);

        colorPicker1.setColor(Cfg.colorGuardies);
        colorPicker2.setColor(Cfg.colorSignaTard);
        colorPicker3.setColor(Cfg.colorFalta);
        colorPicker4.setColor(Cfg.colorFaltaJustificada);
        colorPicker5.setColor(Cfg.colorFaltenXSignar);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jValidaSortida = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jActivaTarda = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jValidarse = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jMissatges = new com.toedter.components.JSpinField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMinRetras = new com.toedter.components.JSpinField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jNClicks = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLookFeel = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTipusLletra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jMidaLletra = new com.toedter.components.JSpinField();
        jLabel12 = new javax.swing.JLabel();
        jAlturaCella = new com.toedter.components.JSpinField();
        jLabel13 = new javax.swing.JLabel();
        jTactil = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        colorPicker1 = new org.iesapp.modules.guardies.dialogs.cfg.ColorPicker();
        colorPicker2 = new org.iesapp.modules.guardies.dialogs.cfg.ColorPicker();
        colorPicker3 = new org.iesapp.modules.guardies.dialogs.cfg.ColorPicker();
        colorPicker4 = new org.iesapp.modules.guardies.dialogs.cfg.ColorPicker();
        colorPicker5 = new org.iesapp.modules.guardies.dialogs.cfg.ColorPicker();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Interactivitat"));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("Requereix validar la sortida");
        jLabel1.setName("jLabel1"); // NOI18N

        jValidaSortida.setName("jValidaSortida"); // NOI18N

        jLabel2.setText("Activa el torn de tarda");
        jLabel2.setName("jLabel2"); // NOI18N

        jActivaTarda.setName("jActivaTarda"); // NOI18N

        jLabel3.setText("Requereix validar-se per signar");
        jLabel3.setName("jLabel3"); // NOI18N

        jValidarse.setName("jValidarse"); // NOI18N

        jLabel7.setText("Minuts per mostrar missatges admin");
        jLabel7.setName("jLabel7"); // NOI18N

        jMissatges.setMaximum(60);
        jMissatges.setMinimum(0);
        jMissatges.setName("jMissatges"); // NOI18N
        jMissatges.setValue(15);

        jLabel14.setText("* 0 = desactivat");
        jLabel14.setName("jLabel14"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jValidarse)
                            .addComponent(jActivaTarda)
                            .addComponent(jValidaSortida))
                        .addContainerGap(384, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMissatges, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(282, 282, 282))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jValidaSortida))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jActivaTarda)
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jValidarse)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jMissatges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Polítiques"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel4.setText("Minuts de retràs que permet signar");
        jLabel4.setName("jLabel4"); // NOI18N

        jMinRetras.setMaximum(60);
        jMinRetras.setMinimum(0);
        jMinRetras.setName("jMinRetras"); // NOI18N
        jMinRetras.setValue(15);

        jLabel8.setText("* 0 = desactivat");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setText("Nombre de clics per signar");
        jLabel9.setName("jLabel9"); // NOI18N

        jNClicks.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Un", "Dos" }));
        jNClicks.setSelectedIndex(1);
        jNClicks.setName("jNClicks"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNClicks, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMinRetras, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jMinRetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jNClicks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Visual"));
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel5.setText("Look & Feel");
        jLabel5.setName("jLabel5"); // NOI18N

        jLookFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nimbus", "System" }));
        jLookFeel.setName("jLookFeel"); // NOI18N

        jLabel10.setText("Tipus font lletra");
        jLabel10.setName("jLabel10"); // NOI18N

        jTipusLletra.setText("Helvetica");
        jTipusLletra.setName("jTipusLletra"); // NOI18N

        jLabel11.setText("Mida de la lletra");
        jLabel11.setName("jLabel11"); // NOI18N

        jMidaLletra.setMaximum(24);
        jMidaLletra.setMinimum(8);
        jMidaLletra.setName("jMidaLletra"); // NOI18N
        jMidaLletra.setValue(11);

        jLabel12.setText("Alçada de les cel·les de les taules");
        jLabel12.setName("jLabel12"); // NOI18N

        jAlturaCella.setMaximum(100);
        jAlturaCella.setMinimum(1);
        jAlturaCella.setName("jAlturaCella"); // NOI18N
        jAlturaCella.setValue(32);

        jLabel13.setText("Habilita pantalla tàctil");
        jLabel13.setName("jLabel13"); // NOI18N

        jTactil.setName("jTactil"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jMidaLletra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTipusLletra)
                            .addComponent(jLookFeel, 0, 80, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAlturaCella, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jTactil)
                                .addGap(26, 26, 26)))))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLookFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTipusLletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMidaLletra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jAlturaCella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTactil))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Colors"));
        jPanel4.setName("jPanel4"); // NOI18N

        jLabel6.setText("Informes. Signa tard");
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel15.setText("Informes. Falta");
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText("Informes. Falta Justificada");
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText("Color guàrdies");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText("Informes. Queden per signar");
        jLabel18.setName("jLabel18"); // NOI18N

        colorPicker1.setName("colorPicker1"); // NOI18N

        colorPicker2.setName("colorPicker2"); // NOI18N

        colorPicker3.setName("colorPicker3"); // NOI18N

        colorPicker4.setName("colorPicker4"); // NOI18N

        colorPicker5.setName("colorPicker5"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPicker5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPicker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPicker4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(colorPicker3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(colorPicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPicker4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPicker5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateIniValues()
    {
        cfg.validaSortida = jValidaSortida.isSelected();
        cfg.activaTarda = jActivaTarda.isSelected();
        cfg.valida = jValidarse.isSelected();
        cfg.activaMissatges = jMissatges.getValue();
        cfg.activaPolicy = jMinRetras.getValue();

        cfg.nClick = jNClicks.getSelectedIndex()+1;
        cfg.lookAndFeel = (String) jLookFeel.getSelectedItem();
        cfg.fontName = jTipusLletra.getText();
        cfg.fontSize = jMidaLletra.getValue();
        cfg.alturaCella = jAlturaCella.getValue();
        cfg.tactil = jTactil.isSelected()? 1:0;

        Cfg.colorGuardies = colorPicker1.getColor();
        Cfg.colorSignaTard = colorPicker2.getColor();
        Cfg.colorFalta = colorPicker3.getColor();
        Cfg.colorFaltaJustificada = colorPicker4.getColor();
        Cfg.colorFaltenXSignar = colorPicker5.getColor();

        cfg.saveIni();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.iesapp.modules.guardies.dialogs.cfg.ColorPicker colorPicker1;
    private org.iesapp.modules.guardies.dialogs.cfg.ColorPicker colorPicker2;
    private org.iesapp.modules.guardies.dialogs.cfg.ColorPicker colorPicker3;
    private org.iesapp.modules.guardies.dialogs.cfg.ColorPicker colorPicker4;
    private org.iesapp.modules.guardies.dialogs.cfg.ColorPicker colorPicker5;
    private javax.swing.JCheckBox jActivaTarda;
    private com.toedter.components.JSpinField jAlturaCella;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jLookFeel;
    private com.toedter.components.JSpinField jMidaLletra;
    private com.toedter.components.JSpinField jMinRetras;
    private com.toedter.components.JSpinField jMissatges;
    private javax.swing.JComboBox jNClicks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox jTactil;
    private javax.swing.JTextField jTipusLletra;
    private javax.swing.JCheckBox jValidaSortida;
    private javax.swing.JCheckBox jValidarse;
    // End of variables declaration//GEN-END:variables

}
