/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnviaMissatges.java
 *
 * Created on 11-may-2011, 8:23:36
 */

package org.iesapp.modules.guardies.dialogs;

import ch.swingfx.twinkle.NotificationBuilder;
import ch.swingfx.twinkle.style.INotificationStyle;
import ch.swingfx.twinkle.style.theme.DarkDefaultNotification;
import ch.swingfx.twinkle.window.Positions;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.iesapp.database.MyDatabase;
import org.iesapp.framework.table.MyCheckBoxRenderer;
import org.iesapp.framework.table.TextAreaEditor;
import org.iesapp.framework.table.TextAreaRenderer;
import org.iesapp.modules.guardies.GuardiesModule;
import org.iesapp.modules.guardies.informes.DadesFaltesAcumulades;
import org.iesapp.modules.guardies.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class EnviaMissatges extends javax.swing.JDialog {
    private boolean isListening=false;
    private DefaultTableModel modelTable1;
    private DefaultTableModel modelTable2;

    private GuardiesModule parent;
    private MyDatabase sgd;
    private final Cfg cfg;

    /** Creates new form EnviaMissatges */
    public EnviaMissatges(GuardiesModule par, boolean modal, Cfg cfg) {
        super((JFrame) null, modal);
        this.cfg = cfg;
        parent = par;
        initComponents();
         jTable1.setIntercellSpacing( new java.awt.Dimension(2,2) );
         jTable1.setGridColor(java.awt.Color.gray);
         jTable1.setShowGrid(true);


        String profes[] = new String[GuardiesModule.abrev2prof.size()];
        int i = 0;
        for(String ky: GuardiesModule.abrev2prof.keySet())
        {
            profes[i] = GuardiesModule.abrev2prof.get(ky)+ " ["+ky+"]";
            i +=1;
        }
        autoCompleteCombo1.setData(profes);

        
        
        if(GuardiesModule.abrev2prof.containsKey(cfg.getCoreCfg().getUserInfo().getAbrev()))
        {
            String txt = GuardiesModule.abrev2prof.get(cfg.getCoreCfg().getUserInfo().getAbrev())+ " ["+cfg.getCoreCfg().getUserInfo().getAbrev()+"]";
            autoCompleteCombo1.setSelectedItem(txt);
        }
        else if(GuardiesModule.abrev2prof.containsKey(cfg.remiteMissatges))
        {
            String txt = GuardiesModule.abrev2prof.get(cfg.remiteMissatges)+ " ["+cfg.remiteMissatges+"]";
            autoCompleteCombo1.setSelectedItem(txt);
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jLabel2 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        autoCompleteCombo1 = new org.iesapp.modules.guardies.util.AutoCompleteCombo();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Envia missatges");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/exit.gif"))); // NOI18N
        jButton1.setText("Tanca");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        modelTable1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Marca", "Per a", "Missatge"
            }
        );
        jTable1.setModel(modelTable1);
        JCheckBox checkbox = new JCheckBox("");
        checkbox.setHorizontalAlignment(SwingConstants.CENTER);

        jTable1.getColumnModel().getColumn(0).setCellEditor( new DefaultCellEditor( checkbox ) );
        jTable1.getColumnModel().getColumn(0).setCellRenderer(new MyCheckBoxRenderer());
        jTable1.getColumnModel().getColumn(2).setCellEditor(new TextAreaEditor());
        jTable1.getColumnModel().getColumn(2).setCellRenderer(new TextAreaRenderer());
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.setRowHeight(32);
        jScrollPane1.setViewportView(jTable1);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Marca'ls tots");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("De:");

        jMonthChooser1.setLocale(new java.util.Locale("ca"));
        jMonthChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jMonthChooser1PropertyChange(evt);
            }
        });

        jLabel2.setText("Mes");

        jYearChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jYearChooser1PropertyChange(evt);
            }
        });

        jLabel3.setText("Any");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/genera.gif"))); // NOI18N
        jButton3.setText("Genera");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Composició del missatge"));

        jTextField1.setText("Us pregam que justifiqueu les faltes de dia ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "#dies", "#n.dies" }));
        jComboBox1.setSelectedIndex(1);

        jTextField2.setText(" Prefectura.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        autoCompleteCombo1.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autoCompleteCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMonthChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jMonthChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(autoCompleteCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/envia.gif"))); // NOI18N
        jButton2.setText("Envia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1))
        );

        jTabbedPane1.addTab("Crea Missatges", jPanel1);

        modelTable2 = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "De", "Per a", "Data", "Missatge"
            }
        );
        jTable2.setModel(modelTable2);
        jScrollPane2.setViewportView(jTable2);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/delete.gif"))); // NOI18N
        jButton4.setText("Esborra'ls");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Còpia d'Enviats", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        isListening=false;
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //genera (ha de llegir un objecte de faltesAcumulades), passant-li com a
    //parametres  abrev, mes i l'any.
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        genera();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void genera()
    {
         this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        
        //esborra taula
        while(jTable1.getRowCount()>0) {
            modelTable1.removeRow(0);
        }

        int mes = jMonthChooser1.getMonth();
        int any = jYearChooser1.getYear();
        for(String ky: GuardiesModule.abrev2prof.keySet())
        {
           Object[] profeMes = new DadesFaltesAcumulades(cfg).getInfoMes(ky, mes, any);
           String dies = "";
           for(int i=0; i<31; i++)
           {
               String anyred = ""+(any-2000);
               
               //Atenció només envia missatges si hi ha falta
                if(profeMes[i].equals("F")) {
                    dies += ""+(i+1)+"/"+(mes+1)+"/"+anyred+"; ";
                }
           }

           String missatge="";
           if(dies.length() != 0)
           {
               missatge = jTextField1.getText();
               if(jComboBox1.getSelectedIndex()==1) {
                    missatge += dies;
                }
               missatge += jTextField2.getText();
           }
           String profe = GuardiesModule.abrev2prof.get(ky)+" ["+ky+"]";
           int idProfe = ( GuardiesModule.abrev2sgdID.get(ky) ).intValue();
           
           //No mostra si no te cap falta o si no té associada cap pda al sistema sgd
           if(missatge.length() != 0 && idProfe>0 ) {
                modelTable1.insertRow(jTable1.getRowCount(), new Object[]{true, profe, missatge});
            }
        }
        
          this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                
    }


    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean tots = jCheckBox1.isSelected();
       
        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            modelTable1.setValueAt(tots, i, 0);
        }

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(jTable1.isEditing()) {
            jTable1.editCellAt(0, 0);
        }

        int nmissatges = 0;

        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            boolean checked = (Boolean) jTable1.getValueAt(i, 0);
            if( checked ) {
                nmissatges += 1;
            }
        }

        if(nmissatges ==0 ) {
            return;
        }
        String remite = (String) autoCompleteCombo1.getSelectedItem();
        if(remite== null) {
            remite="";
        }
        remite = remite.toUpperCase();
        String remite_abrev = StringUtils.AfterLast(remite, "[");
        remite_abrev = StringUtils.BeforeLast(remite_abrev, "]").trim();

        

        if(!GuardiesModule.abrev2sgdID.containsKey(remite_abrev))
        {
                   INotificationStyle style = new DarkDefaultNotification().withWindowCornerRadius(8).withWidth(300).withAlpha(0.86f);

                  // Now lets build the notification
                     new NotificationBuilder().withStyle(style) // Required. here we set the previously set style
                        .withTitle("Atenció") // Required.
                        .withMessage("Cal elegir un remitent vàlid") // Optional
                        .withIcon(new ImageIcon(NotificationBuilder.ICON_EXCLAMATION)) // Optional. You could also use a String path
                        .withDisplayTime(3000) // Optional
                        .withPosition(Positions.NORTH_EAST) // Optional. Show it at the center of the screen
                        .showNotification(); // this returns a UUID that you can use to identify events on the listener

            return;
        }

        int idRemite = (GuardiesModule.abrev2sgdID.get(remite_abrev)).intValue();

        int conf = JOptionPane.showConfirmDialog(null, remite + "\nestà a punt d'enviar "
                    +nmissatges+" missatges.\nVoleu continuar?", "Confirmacio",
                                      JOptionPane.YES_NO_OPTION);
        
        if (conf!=0) {
            return;
        }

         for(int i=0; i<jTable1.getRowCount(); i++)
        {
            boolean checked = (Boolean) jTable1.getValueAt(i, 0);
            if( checked )
            {
                
                    String texto = (String) jTable1.getValueAt(i, 2);
                    String profe = ((String) jTable1.getValueAt(i,1)).toUpperCase();
                    profe = StringUtils.AfterLast(profe, "[");
                    profe = StringUtils.BeforeLast(profe, "]");
                    int idProfe = ( GuardiesModule.abrev2sgdID.get(profe) ).intValue();
    
                    String SQL1 = "INSERT INTO mensajes (fecha, texto, idUsuarios, idProfesores) " + " VALUES( '" + parent.ctrlDia + "', ?, " + "'"+idRemite+"', '"+idRemite+"' )";
                   // System.out.println(SQL1);
                    int idmax = sgd.preparedUpdateID(SQL1, new Object[]{texto});

                    int nup2 = 0;
                    if(idmax>0)
                    {
                        SQL1 = "INSERT INTO mensajesprofesores (idMensajes, idProfesores) " + " VALUES( '" + idmax + "', " + idProfe + ")";
                        nup2 = sgd.executeUpdate(SQL1);
                    }
                    
                    //Només si s'ha conseguit dur a terme l'operacio deixa una CC
                    if(idmax>0 && nup2>0)
                    {
                        SQL1 = "INSERT INTO "+Cfg.prefix+"missatges (de, para, data, missatge, instantani) " + " VALUES( '"
                            + GuardiesModule.abrev2prof.get(remite_abrev) + "', '" + GuardiesModule.abrev2prof.get(profe) + 
                            "', '"+ parent.ctrlDia+ "', ?, 0)";
                        int nup =cfg.getCoreCfg().getMysql().preparedUpdate(SQL1, new Object[]{texto});
                    }

               
                        
            }
            
        }
            jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
       
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

        if(modelTable2==null) {
            return;
        }

        //esborra la taula
        while(jTable2.getRowCount()>0) {
            modelTable2.removeRow(0);
        }
        

        try {
            String SQL1 = "Select * from " + Cfg.prefix + "missatges where instantani=0 order by data desc";
            Statement st =cfg.getCoreCfg().getMysql().createStatement();
            ResultSet rs1 =cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
            while (rs1 != null && rs1.next()) {
                String de = rs1.getString("de");
                String para = rs1.getString("para");
                String data = rs1.getString("data");
                String missatge = rs1.getString("missatge");

                modelTable2.insertRow(jTable2.getRowCount(), new Object[]{de, para, data, missatge});
            }
            if(rs1!=null) {
                rs1.close();
                st.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EnviaMissatges.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        
        int conf = JOptionPane.showConfirmDialog(null, "Voleu esborrar la còpia dels\n"+
                    "missatges enviats?", "Confirmacio",
        JOptionPane.YES_NO_OPTION);
        
        if (conf!=0) {
            return;
        }

        
        //esborra la taula
        while(jTable2.getRowCount()>0) {
            modelTable2.removeRow(0);
        }

        String SQL1 = "DELETE FROM "+Cfg.prefix+"missatges WHERE id>=1 and instantani = 0";
        int nup = cfg.getCoreCfg().getMysql().executeUpdate(SQL1);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMonthChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jMonthChooser1PropertyChange
        if(!isListening) {
            return;
        }
        genera();
    }//GEN-LAST:event_jMonthChooser1PropertyChange

    private void jYearChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jYearChooser1PropertyChange
        if(!isListening) {
            return;
        }
        genera();
    }//GEN-LAST:event_jYearChooser1PropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //crea una nova connexio a la base de dades de l'SGD
        sgd = cfg.getCoreCfg().getSgd();
        if(sgd.isClosed())
        {
                   INotificationStyle style = new DarkDefaultNotification().withWindowCornerRadius(8).withWidth(300).withAlpha(0.86f);

                  // Now lets build the notification
                     new NotificationBuilder().withStyle(style) // Required. here we set the previously set style
                        .withTitle("Error") // Required.
                        .withMessage("La base de dades de missatges no està ben configurada.") // Optional
                        .withIcon(new ImageIcon(NotificationBuilder.ICON_ERROR)) // Optional. You could also use a String path
                        .withDisplayTime(5000) // Optional
                        .withPosition(Positions.NORTH_EAST) // Optional. Show it at the center of the screen
                        .showNotification(); // this returns a UUID that you can use to identify events on the listener

            isListening = false;
            this.dispose();
        }

        isListening = true;
    }//GEN-LAST:event_formWindowOpened

    @Override
   protected JRootPane createRootPane() {
    JRootPane rootPane2 = new JRootPane();
    KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
    Action actionListener = new AbstractAction() {
      public void actionPerformed(ActionEvent actionEvent) {
        setVisible(false);
      }
    } ;
    InputMap inputMap = rootPane2.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
    inputMap.put(stroke, "ESCAPE");
    rootPane2.getActionMap().put("ESCAPE", actionListener);

    return rootPane2;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.iesapp.modules.guardies.util.AutoCompleteCombo autoCompleteCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    // End of variables declaration//GEN-END:variables

 
}
