/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EsborraSig.java
 *
 * Created on 17-ene-2012, 0:03:41
 */
package org.iesapp.modules.guardies.dialogs;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.iesapp.framework.util.CoreCfg;
import org.iesapp.util.DataCtrl;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class EsborraSig extends javax.swing.JDialog {
    private boolean isListening=false;
    private final CoreCfg coreCfg;

    /** Creates new form EsborraSig */
    public EsborraSig(java.awt.Frame parent, boolean modal, java.util.Date date, CoreCfg coreCfg) {
        super(parent, modal);
        this.coreCfg = coreCfg;
        initComponents();
        jDateChooser1.setDate(date);
        isListening = true;
        checkSignatures();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Esborra Signatures");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Aneu amb compte. Una vegada esborrades, les signatures no són recuperables.");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/delete.gif"))); // NOI18N
        jButton1.setText("Esborra");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/exit.gif"))); // NOI18N
        jButton2.setText("Surt");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Esborra Signatures de dia");
        jLabel2.setName("jLabel2"); // NOI18N

        jDateChooser1.setName("jDateChooser1"); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Log");
        jLabel3.setName("jLabel3"); // NOI18N

        jCheckBox1.setSelected(true);
        jCheckBox1.setText(" Esborra el dia complet");
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Converteix les `No signats` de la franja horaria");
        jCheckBox2.setName("jCheckBox2"); // NOI18N
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("(Ex. 2-4, des de la 2a a la 4a hora)");
        jLabel4.setName("jLabel4"); // NOI18N

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("a l'estat Signat");
        jCheckBox3.setEnabled(false);
        jCheckBox3.setName("jCheckBox3"); // NOI18N
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("a l'estat Hora buida");
        jCheckBox4.setEnabled(false);
        jCheckBox4.setName("jCheckBox4"); // NOI18N
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jTextField1.setText("1-2");
        jTextField1.setEnabled(false);
        jTextField1.setName("jTextField1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(385, 385, 385)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jCheckBox4)
                                                .addComponent(jCheckBox3)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
      checkSignatures();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void checkSignatures()
    {
         if(!isListening) {
            return;
        }
        
        jTextArea1.append("Dia "+jDateChooser1.getDate()+"\n");
        //Comprova si el dia triat té o no signatures
        String SQL1 = "Select count(id) as total from sig_signatures where data='"+new DataCtrl(jDateChooser1.getDate()).getDataSQL()+"'";
        try {
            Statement st =coreCfg.getMysql().createStatement();
            ResultSet rs1 =coreCfg.getMysql().getResultSet(SQL1,st);
            if(rs1!=null && rs1.next())
            {
                jTextArea1.append("> Núm. signatures matí="+rs1.getInt("total")+"\n");
            }
            if(rs1!=null) {
                rs1.close();
                st.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EsborraSig.class.getName()).log(Level.SEVERE, null, ex);
        }
            //Comprova si el dia triat té o no signatures
        SQL1 = "Select count(id) as total from sig_signatures_tarda where data='"+new DataCtrl(jDateChooser1.getDate()).getDataSQL()+"'";
        try {
            Statement st =coreCfg.getMysql().createStatement();
            ResultSet rs1 =coreCfg.getMysql().getResultSet(SQL1,st);
            if(rs1!=null && rs1.next())
            {
                jTextArea1.append("> Núm. signatures tarda="+rs1.getInt("total")+"\n");
            }
            if(rs1!=null) {
                rs1.close();
                st.close();
            }
        } catch (SQLException ex) {
            Logger.getLogger(EsborraSig.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.append("\n");
    }
    
    
    //ESBORRA
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jCheckBox2.isSelected() && jTextField1.getText().length() == 0)
        {
            jTextField1.setFocusable(true);
            return;
        }
        
        
        DataCtrl cd = new DataCtrl( jDateChooser1.getDate() );
        
        if(jCheckBox1.isSelected())
        {
            
            //Confirmació    
             int conf = JOptionPane.showConfirmDialog(this, "Estau a punt d'esborrar les "
                     + "signatures del dia "+cd.getDiaMesComplet()+"\nVoleu continuar?", "Confirmacio",
                                      JOptionPane.YES_NO_OPTION);
        
             if (conf!=0) {
                return;
            }

            
            //Tot el dia
            String SQL1 = "DELETE FROM sig_data where data='"+cd.getDataSQL()+"'";
            int nup =coreCfg.getMysql().executeUpdate(SQL1);
            jTextArea1.append("sig_data: esborrades "+nup+"entrades\n");
            SQL1 = "DELETE FROM sig_signatures where data='"+cd.getDataSQL()+"'";
            nup =coreCfg.getMysql().executeUpdate(SQL1);
            jTextArea1.append("sig_signatures: esborrades "+nup+"entrades\n");
            SQL1 = "DELETE FROM sig_signatures_tarda where data='"+cd.getDataSQL()+"'";
            nup =coreCfg.getMysql().executeUpdate(SQL1);
            jTextArea1.append("sig_signatures_tarda: esborrades "+nup+"entrades\n");
            jTextArea1.append("Fet!\n");
            
            checkSignatures();            
        }
        else
        {
            //Una franja
            //Determina inici i fi de la franja
            int ini = -1;
            int fin = -1;
            
            String sini = StringUtils.BeforeFirst(jTextField1.getText(), "-");
            String sfin = StringUtils.AfterFirst(jTextField1.getText(), "-");
            
            try
            {
                ini = Integer.parseInt(sini);
                fin = Integer.parseInt(sfin);
            }
            catch(java.lang.NumberFormatException e)
            {
                //
            }
            
            if(ini<=0 || fin<=0) {
                return;
            }
            
            if(fin<ini)
            {
                int ini0 = ini;
                ini = fin;
                fin = ini0;
            }
            
             //Confirmació    
             int conf = JOptionPane.showConfirmDialog(this, "Estau a punt de convertir "
                     + "signatures ``?´´ del dia "+cd.getDiaMesComplet()+"\nen la franja "+ini+"a - "
                     +fin+"a hores.\nVoleu continuar?", "Confirmacio",
                                      JOptionPane.YES_NO_OPTION);
        
             int newStatus = 1;
             if(jCheckBox4.isSelected()) {
                newStatus = -1;
            }
             
             if (conf!=0) {
                return;
            }
             
             for(int i=ini; i<=fin; i++)
             {
                if(i<8)
                {
                     String SQL1 = "UPDATE sig_signatures SET h"+i+"="+newStatus+
                             " where data='"+cd.getDataSQL()+"' AND h"+i+"=0";
                     int nup =coreCfg.getMysql().executeUpdate(SQL1);
                     jTextArea1.append(" > sig_signatures: hora="+i+": convertits="+nup+"\n");
                }
                else if(i>=8 && i<15)
                {
                     String SQL1 = "UPDATE sig_signatures_tarda SET h"+(i-7)+"="+newStatus+
                             " where data='"+cd.getDataSQL()+"' AND h"+(i-7)+"=0";
                     int nup =coreCfg.getMysql().executeUpdate(SQL1);
                     jTextArea1.append(" > sig_signatures_tarda: hora="+i+": convertits="+nup+"\n");
                }
             }
             jTextArea1.append("Fet!\n");
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        isListening = false;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        updateUI(1);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
         updateUI(2);
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        updateUI(3);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        updateUI(4);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

   
    private void updateUI(int id) {
        switch(id)
        {
            case 1:
                if(jCheckBox1.isSelected())
                {
                    jCheckBox2.setSelected(false);
                    jTextField1.setEnabled(false);
                    jCheckBox3.setEnabled(false);
                    jCheckBox4.setEnabled(false);
                }
                else
                {
                    jCheckBox2.setSelected(true);
                    jTextField1.setEnabled(true);
                    jCheckBox3.setEnabled(true);
                    jCheckBox4.setEnabled(true);
                }
                break;
            case 2:
                if(jCheckBox2.isSelected())
                {
                    jCheckBox1.setSelected(false);
                    jTextField1.setEnabled(true);
                    jCheckBox3.setEnabled(true);
                    jCheckBox4.setEnabled(true);
                }
                else
                {
                    jCheckBox1.setSelected(true);                
                    jTextField1.setEnabled(false);
                    jCheckBox3.setEnabled(false);
                    jCheckBox4.setEnabled(false);
                }
                break;
            case 3:
                if(jCheckBox3.isSelected())
                {
                    jCheckBox4.setSelected(false);
                }
                else
                {
                    jCheckBox4.setSelected(true);
                }
                   
                break;
            case 4:
                if(jCheckBox4.isSelected())
                {
                    jCheckBox3.setSelected(false);
                }
                else
                {
                    jCheckBox3.setSelected(true);
                }
                   
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
