/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.iesapp.modules.guardies;

import com.toedter.calendar.JSpinnerDateEditor;
import java.awt.Color;
import java.beans.PropertyChangeListener;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.iesapp.clients.iesdigital.dates.DatesControl;
import org.iesapp.modules.guardies.util.Cfg;
import org.iesapp.modules.guardies.util.ControlData;

/**
 *
 * @author Josep
 */
public class DateChooser extends JPanel {
    private final String[] diesSetmana;
    private final Color colorFestiu;
    private final Cfg cfg;

    /**
     * Creates new form DateChooser
     */
    public DateChooser(java.util.Date date, Cfg cfg) {
        initComponents();
        this.cfg = cfg;
        jDateChooser1.setDate(date);
        diesSetmana = new String[] {"Dl.", "Dt.", "Dm.", "Dj.", "Dv.", "Ds.", "Dg."};
        colorFestiu = new Color(255,190,190);
        jIconDay.setVisible(false);

    }
    
    public void addChangeDateListener(PropertyChangeListener listener)
    {
        jDateChooser1.addPropertyChangeListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDay = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser(null, null, null, new JSpinnerDateEditor());
        jIconDay = new javax.swing.JLabel();

        jDay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDay.setText("Dl.");

        java.util.Locale mlocale = new java.util.Locale( "ca", "ES", "" );

        jDateChooser1.setLocale(mlocale);
        jDateChooser1.setToolTipText("Selecciona data");
        jDateChooser1.setPreferredSize(new java.awt.Dimension(154, 28));

        jIconDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/diaalert.gif"))); // NOI18N
        jIconDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconDayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jDay)
                .addGap(5, 5, 5)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jIconDay))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jDay))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jIconDay))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jIconDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconDayMouseClicked
        ControlData cd = new ControlData(cfg);
        jDateChooser1.setDate(cd.getDate());
        formataData();
    }//GEN-LAST:event_jIconDayMouseClicked

    public void formataData()
    {
       ControlData cd = new ControlData(cfg);
       String ara = cd.getDiaMesComplet();
       
       //Triat
       ControlData cd2 = new ControlData(jDateChooser1.getDate(),cfg);
       String triat = cd2.getDiaMesComplet();

       if(ara.equals(triat))
       {
          jIconDay.setIcon(null);
          jIconDay.setToolTipText(null);
        }
        else
        {
          jIconDay.setIcon(  new ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/diaalert.gif")) );
          jIconDay.setToolTipText("Torna al dia d'avui");
       }

       if(cd2.getIntDia()>5 || new DatesControl(cd2.getDate(),cfg.getCoreCfg().getIesClient()).esFestiu())
       {
             jDay.setOpaque(true);
             jDay.setBackground(colorFestiu);
             jDay.setToolTipText("Festiu");
       }
       else
       {
             jDay.setOpaque(false);
             jDay.setToolTipText(null);
       }
      jDay.setText(diesSetmana[cd2.getIntDia()-1]);


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jDay;
    private javax.swing.JLabel jIconDay;
    // End of variables declaration//GEN-END:variables

    public void removeChangeDateListener(PropertyChangeListener propertyChangeListener) {
        jDateChooser1.removePropertyChangeListener(propertyChangeListener);
    }

    public void setDate(Date date) {
        jDateChooser1.setDate(date);
    }
    
    public Date getDate() {
        return jDateChooser1.getDate();
    }
     
    @Override
    public void setEnabled(boolean b)
    {
        jDateChooser1.setEnabled(b);
    }
    
   
}
