/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InformesGuardies.java
 *
 * Created on 11-jun-2011, 10:37:44
 */

package org.iesapp.modules.guardies.informes;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.iesapp.modules.guardies.GuardiesModule;
import org.iesapp.modules.guardies.util.Cfg;
import org.iesapp.util.StringUtils;

/**
 *
 * @author Josep
 */
public class InformesGuardies extends javax.swing.JDialog {
    private final Cfg cfg;


    /** Creates new form InformesGuardies */
    public InformesGuardies(java.awt.Frame par, boolean modal, Cfg cfg) {
        super(par, modal);
        initComponents();
        this.cfg = cfg;
       

        String profes[] = new String[GuardiesModule.abrev2prof.size()];
        int i = 0;
        for(String ky: GuardiesModule.abrev2prof.keySet())
        {
            profes[i] = GuardiesModule.abrev2prof.get(ky)+ " ["+ky+"]";
            i +=1;
        }
        autoCompleteCombo1.setData(profes);
        DefaultComboBoxModel model =new DefaultComboBoxModel();
        model.addElement(StringUtils.anyAcademic());
        jComboBox1.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        autoCompleteCombo1 = new org.iesapp.modules.guardies.util.AutoCompleteCombo();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        }
        ;
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informe de guàrdies realitzades");

        autoCompleteCombo1.setName("autoCompleteCombo1"); // NOI18N
        autoCompleteCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoCompleteCombo1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010-2011" }));
        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel1.setText("Professor");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Curs");
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        modelTable1 = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Grup/Aula", "Substitució"
            }
        );

        jTable1.setModel(modelTable1);
        jTable1.getTableHeader().setReorderingAllowed(false);

        jTable1.setRowHeight(32);

        TableColumn col = jTable1.getColumnModel().getColumn(2);
        col.setPreferredWidth(160);
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/iesapp/modules/guardies/icons/exit.gif"))); // NOI18N
        jButton1.setText("Tanca");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Dies");
        jLabel3.setName("jLabel3"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tots els dies", "Dilluns", "Dimarts", "Dimecres", "Dijous", "Divendres" }));
        jComboBox2.setName("jComboBox2"); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, 0, 301, Short.MAX_VALUE)
                            .addComponent(autoCompleteCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(autoCompleteCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //Selecciona
    private void autoCompleteCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoCompleteCombo1ActionPerformed
       fillTable();
    }//GEN-LAST:event_autoCompleteCombo1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       fillTable();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void fillTable()
    {
         int id = autoCompleteCombo1.getSelectedIndex();
        if(id>=0)
        {
             String profe = (String) autoCompleteCombo1.getSelectedItem();
             if(profe== null) {
                profe="";
            }
             profe = profe.toUpperCase();
             String profe_abrev = StringUtils.AfterLast(profe, "[");
             profe_abrev = StringUtils.BeforeLast(profe_abrev, "]").trim();

     
             if(!GuardiesModule.abrev2prof.containsKey(profe_abrev)) {
                return;
            }

             int sel = jComboBox2.getSelectedIndex();
             String condition ="";
             if(sel>0)
             {
                    condition = " AND dia_setmana='"+sel+"' ";
             }


             String SQL1 = "Select * from sig_diari_guardies where profe_guarda='"
                     +profe_abrev+"' " + condition + " order by data";
             
            

             while(jTable1.getRowCount()>0) {
                modelTable1.removeRow(0);
            }


             try {
                  Statement st = cfg.getCoreCfg().getMysql().createStatement();
                  ResultSet rs1 = cfg.getCoreCfg().getMysql().getResultSet(SQL1,st);
                 
                  while (rs1 != null && rs1.next()) {
                    String data = rs1.getString("data");
                    String grup = rs1.getString("grup");
                    String abrev_falta = rs1.getString("profe_falta");
                    String profe_falta = GuardiesModule.abrev2prof.get(abrev_falta);

                    modelTable1.addRow(new Object[]{StringUtils.Sql2EUData(data,2), grup, profe_falta});
                }
                if(rs1!=null){
                 rs1.close();
                 st.close();
             }
            } catch (SQLException ex) {
                Logger.getLogger(InformesGuardies.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

   protected JRootPane createRootPane() {
    JRootPane rootPane2 = new JRootPane();
    KeyStroke stroke = KeyStroke.getKeyStroke("ESCAPE");
    AbstractAction actionListener = new AbstractAction() {
      public void actionPerformed(ActionEvent actionEvent) {
        setVisible(false);
      }
    } ;
    InputMap inputMap = rootPane2.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
    inputMap.put(stroke, "ESCAPE");
    rootPane2.getActionMap().put("ESCAPE", actionListener);

    return rootPane2;
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.iesapp.modules.guardies.util.AutoCompleteCombo autoCompleteCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelTable1;
    
}
